### ISSUE TITLE
Org list is empty

### ISSUE THREAD

**Issue by sodeglor** [drossi750/vscode-salesforce-toolkit#16] opened 2022-08-07 15:54 UTC
Type: <b>Bug</b>

<img width="333" alt="Screenshot 2022-08-07 at 17 54 07" src="https://user-images.githubusercontent.com/110778976/183299588-46aa5433-ed05-48c1-a8d4-1317bce96b7a.png">
I have reinstalled Salesforce Toolkit, disabled and enabled it again, but in the Explorer I cannot see the orgs listed. Thank you for your help!

Extension version: 1.2.4
VS Code version: Code 1.70.0 (Universal) (da76f93349a72022ca4670c1b84860304616aaa2, 2022-08-04T04:38:55.829Z)
OS version: Darwin x64 21.5.0
Modes:

**Comment by Robin-Korver** [comment] 2022-08-23 09:21
Same here.

**Comment by drossi750** [comment] 2022-08-24 13:23
Can you please provide sfdx-cli version?

**Comment by bernadettsinko** [comment] 2022-08-25 07:10
Sure, the sfdx-cli version is v0.0.1

**Comment by Robin-Korver** [comment] 2022-11-10 10:36
I noticed that also the command `sfdx force:org:list` gave an error (JSON parsing error). SF support indicated that this is due to a corrupt auth file. I removed all my auth files from the `.sfdx` folder (on mac, `users/<user>/.sfdx`). This resolved the CLI command issue for me and also made the extension work again.

**Comment by drossi750** [comment] 2022-11-13 10:44
So the issue is outside, broken auth. Closing this.

**Closed by drossi750** 2022-11-13 10:44 UTC
